export const STATUS_MAP: Record<string, string> = {
  'Closed': 'done',
  'In Progress': 'in_progress',
  'in_progress': 'in_progress',
  'Develop In Progress': 'in_progress',
  'Blocked': 'blocked',
  'blocked': 'blocked',
  'Not started': 'todo',
  'Not Started': 'todo',
  'Open / New': 'todo',
  'Todo': 'todo',
  'TODO': 'todo',
  'Yet To Stage': 'in_review',
  'Yet To Deploy': 'in_review',
  'Under Review': 'in_review',
  'In Review': 'in_review',
  'Completed': 'done',
  'Done': 'done',
  'Open': 'todo',
  'Reopen': 'in_progress',
  'Re-opened': 'in_progress',
  'Pending': 'todo',
};

export const PRIORITY_MAP: Record<string, string> = {
  'High': 'HIGH',
  'high': 'HIGH',
  'Critical': 'CRITICAL',
  'critical': 'CRITICAL',
  'Medium': 'MEDIUM',
  'medium': 'MEDIUM',
  'Low': 'LOW',
  'low': 'LOW',
};
